import { writeFile } from "node:fs/promises";
import path from "node:path";
import type { CyphraClient } from "@cyphra/runtime";
import type { CyphraConfig } from "@cyphra/config";
import { clientFromEnv } from "../clientFromEnv.js";

function isValidNodeName(label: string): boolean {
  return /^[A-Za-z_][A-Za-z0-9_]*$/.test(label);
}

/** Minimal session shape for introspection queries (matches neo4j-driver `Session` result typing). */
type BoltSession = {
  run: (
    cypher: string,
    params?: Record<string, unknown>,
  ) => Promise<{
    records: ReadonlyArray<{ keys: ReadonlyArray<string | number>; get: (key: string | number) => unknown }>;
  }>;
};

async function samplePropertyKeysByLabel(
  client: CyphraClient,
  labels: readonly string[],
  cap: number,
): Promise<Map<string, string[]>> {
  const out = new Map<string, string[]>();
  if (cap <= 0) {
    return out;
  }
  await client.withSession(async (session) => {
    for (const label of labels) {
      if (!isValidNodeName(label)) {
        continue;
      }
      try {
        const result = await session.run(
          `MATCH (n:${label}) WITH n LIMIT $k UNWIND keys(n) AS prop RETURN collect(DISTINCT prop) AS props`,
          { k: cap },
        );
        const rec = result.records[0];
        const props = rec?.get("props");
        const list = Array.isArray(props)
          ? [...props].map((x) => String(x)).filter((s) => s.length > 0).sort()
          : [];
        out.set(label, list);
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        process.stderr.write(`cyphra db pull: skipped property sample for :${label}: ${msg}\n`);
        out.set(label, []);
      }
    }
  });
  return out;
}

async function safeSessionRun(session: BoltSession, cypher: string, what: string): Promise<string[]> {
  try {
    const result = await session.run(cypher);
    return result.records.map((rec) => {
      const keys = rec.keys;
      if (keys.length === 1) {
        return String(rec.get(keys[0]!));
      }
      const parts = keys.map((k) => `${k}: ${JSON.stringify(rec.get(k))}`);
      return parts.join(", ");
    });
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    process.stderr.write(`cyphra db pull: skipped ${what}: ${msg}\n`);
    return [];
  }
}

/**
 * Introspect Neo4j metadata into a **draft** `.cyphra` schema (human review required).
 */
export async function runDbPull(
  cwd: string,
  config: CyphraConfig,
  opts: { print?: boolean; force?: boolean; sampleSize?: number },
): Promise<void> {
  const client = clientFromEnv();
  const sampleCap = opts.sampleSize ?? 0;
  try {
    const labels = await client.withSession(async (session) => {
      const rows = await safeSessionRun(
        session,
        "CALL db.labels() YIELD label RETURN label ORDER BY label",
        "db.labels()",
      );
      return rows;
    });

    const relTypes = await client.withSession(async (session) => {
      return safeSessionRun(
        session,
        "CALL db.relationshipTypes() YIELD relationshipType RETURN relationshipType ORDER BY relationshipType",
        "db.relationshipTypes()",
      );
    });

    const constraintRows = await client.withSession(async (session) => {
      return safeSessionRun(session, "SHOW CONSTRAINTS", "SHOW CONSTRAINTS");
    });

    const indexRows = await client.withSession(async (session) => {
      return safeSessionRun(session, "SHOW INDEXES", "SHOW INDEXES");
    });

    const sampledKeys =
      sampleCap > 0 ? await samplePropertyKeysByLabel(client, labels, sampleCap) : new Map<string, string[]>();

    const lines: string[] = [
      "// Generated by `cyphra db pull` — review before relying on ORM / push.",
      "// Neo4j is schema-optional: this file is a hypothesis; add @id / @unique / fields by hand or via `cyphra schema add`.",
      "",
    ];

    if (sampleCap > 0) {
      lines.push(
        `// Property keys below are sampled from up to ${sampleCap} nodes per label (heterogeneous graphs may hide keys).`,
        "",
      );
    }

    if (relTypes.length > 0) {
      lines.push("// Relationship types observed in the database:", "//   " + relTypes.join(", "));
      lines.push("// Map these to `relationship` blocks with explicit from/to labels in your schema.", "");
    }

    if (constraintRows.length > 0) {
      lines.push("// SHOW CONSTRAINTS (align decorators after review):");
      for (const row of constraintRows) {
        lines.push(`//   ${row}`);
      }
      lines.push("");
    }

    if (indexRows.length > 0) {
      lines.push("// SHOW INDEXES (align @index after review):");
      for (const row of indexRows) {
        lines.push(`//   ${row}`);
      }
      lines.push("");
    }

    for (const label of labels) {
      if (!isValidNodeName(label)) {
        lines.push(`// skipped invalid label: ${JSON.stringify(label)}`, "");
        continue;
      }
      const keys = sampledKeys.get(label);
      if (keys && keys.length > 0) {
        lines.push(`//   # inferred keys: ${keys.join(", ")}`, "");
      } else if (sampleCap > 0 && keys !== undefined && keys.length === 0) {
        lines.push("//   (no keys on sampled nodes)", "");
      }
      lines.push(`node ${label} {`, `}`, "");
    }

    const body = lines.join("\n");
    if (opts.print) {
      process.stdout.write(body);
      return;
    }

    const target = config.schema;
    const { readFile } = await import("node:fs/promises");
    try {
      await readFile(target, "utf8");
      if (!opts.force) {
        throw new Error(
          `Schema file already exists: ${target}. Use --print or --force to overwrite.`,
        );
      }
    } catch (e) {
      const err = e as NodeJS.ErrnoException;
      if (err.code !== "ENOENT") throw e;
    }

    await writeFile(target, body, "utf8");
    process.stdout.write(`Wrote draft schema to ${path.relative(cwd, target)}\n`);
  } finally {
    await client.close();
  }
}
