import type { Decorator, SchemaDocument } from "./ast.js";

function decoratorStringArg(
  decorators: readonly Decorator[],
  decoratorName: string,
  argKey: string,
): string | undefined {
  const dec = decorators.find((d) => d.name === decoratorName);
  if (!dec) {
    return undefined;
  }
  const arg = dec.args.find((a) => a.key === argKey);
  if (!arg || arg.value.kind !== "string") {
    return undefined;
  }
  return arg.value.value;
}

/** Data used to emit `cyphra.gen.ts`. */
export type CodegenModel = {
  readonly nodeLabels: readonly string[];
  readonly relationshipModels: readonly {
    readonly name: string;
    readonly neo4jType: string;
    readonly fromLabel: string;
    readonly toLabel: string;
  }[];
  readonly relNeo4jTypes: readonly string[];
};

/**
 * Walk the AST and collect labels, relationship models, and all Neo4j relationship types.
 *
 * @param doc - Validated schema document.
 */
export function collectCodegenModel(doc: SchemaDocument): CodegenModel {
  const nodeLabels: string[] = [];
  const relationshipModels: {
    name: string;
    neo4jType: string;
    fromLabel: string;
    toLabel: string;
  }[] = [];
  const relTypes = new Set<string>();

  for (const decl of doc.declarations) {
    if (decl.kind === "Node") {
      nodeLabels.push(decl.name);
      for (const f of decl.fields) {
        if (f.kind === "Relational") {
          const t = decoratorStringArg(f.decorators, "relationship", "type");
          if (t) {
            relTypes.add(t);
          }
        }
      }
    } else {
      relationshipModels.push({
        name: decl.name,
        neo4jType: decl.relType,
        fromLabel: decl.from,
        toLabel: decl.to,
      });
      relTypes.add(decl.relType);
    }
  }

  return {
    nodeLabels,
    relationshipModels,
    relNeo4jTypes: [...relTypes].sort(),
  };
}

/**
 * Turn a Neo4j relationship type string into a stable `RelType` object key (valid identifier).
 *
 * @param type - Value inside `type: "…"` in the schema.
 */
export function relTypeToExportKey(type: string, used: Set<string>): string {
  let base = type.replace(/[^A-Za-z0-9_]/g, "_");
  if (!base || /^[0-9]/.test(base)) {
    base = `T_${base || "rel"}`;
  }
  let key = base;
  let n = 2;
  while (used.has(key)) {
    key = `${base}_${n++}`;
  }
  used.add(key);
  return key;
}

/**
 * Render a `cyphra.gen.ts` module for use with the query builder and migrations.
 *
 * @param doc - Parsed and validated schema.
 */
export function renderCyphraGenSource(doc: SchemaDocument): string {
  const model = collectCodegenModel(doc);
  const lines: string[] = [];

  lines.push("/**");
  lines.push(" * Generated by `cyphra generate` — do not edit by hand.");
  lines.push(" */");
  lines.push("");
  lines.push("/** Neo4j node labels from `node` declarations. */");
  lines.push("export const NodeLabel = {");
  for (const L of model.nodeLabels) {
    lines.push(`  ${L}: ${JSON.stringify(L)},`);
  }
  lines.push("} as const;");
  lines.push("");
  lines.push("export type NodeLabelName = keyof typeof NodeLabel;");
  lines.push("");

  lines.push("/** Rich `relationship { … }` blocks: Neo4j type + endpoint labels. */");
  lines.push("export const RelationshipSpec = {");
  for (const r of model.relationshipModels) {
    lines.push(`  ${r.name}: {`);
    lines.push(`    neo4jType: ${JSON.stringify(r.neo4jType)},`);
    lines.push(`    fromLabel: ${JSON.stringify(r.fromLabel)},`);
    lines.push(`    toLabel: ${JSON.stringify(r.toLabel)},`);
    lines.push(`  },`);
  }
  lines.push("} as const;");
  lines.push("");
  lines.push("export type RelationshipModelName = keyof typeof RelationshipSpec;");
  lines.push("");

  lines.push("/** Distinct Neo4j relationship types used on fields or declarations. */");
  lines.push("export const RelType = {");
  const usedKeys = new Set<string>();
  for (const t of model.relNeo4jTypes) {
    const key = relTypeToExportKey(t, usedKeys);
    lines.push(`  ${key}: ${JSON.stringify(t)},`);
  }
  lines.push("} as const;");
  lines.push("");
  lines.push("export type RelTypeKey = keyof typeof RelType;");
  lines.push("");

  return lines.join("\n");
}
